name: CI-CD

env: 
  IMAGE_TAGS: latest,${{github.sha}}
  TEST_TAGS: latest,${{github.sha}}


on:
  push:
    branches: main
jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      #   Setup Node
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      # Install dependencies and build
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Run Tests
        run: npm run test
        env:
          CI: true

      - name: Upload artifact to enable deployement
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: "Install Deps"
        run: npm install
      - name: "Test"
        run: npm run coverage


  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Test image
        uses: docker/build-push-action@v5
        with:
          load: true
          tags: ${{ env.TEST_TAG }}
      
      - name: Test built image
        run: |
          docker run --rm ${{ env.TEST_TAGS }}    
          
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{env.IMAGE_TAGS}}
