name: CI-CD
on: 
  push:
      branches:  main
jobs: 
   # Build Job
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            #   Setup Node
            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 18.x

            # Install dependencies and build
            - name: Install Dependencies
              run: npm install
            - name: Build Project
              run: npm run build

            - name: Upload artifact to enable deployement
              uses: actions/upload-artifact@v4
              with: 
                name: production-files
                path: ./dist
    release: 
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: sivuyilemene/task-app
                tags: type=ref,event=push
                
            - name: build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ${{ steps.meta.outputs.tags }}