---

name: CI Pipeline

on: 
  pull_request:
    branches: main


jobs:
  lint-code: 
    name: Lint code base
    runs-on: ubuntu-latest
      
    steps:


      - name: Checkout code
        uses: actions/checkout@v4.1.6

      - name: Setup npm
        run:  npm install
    
      - name: Run linter on code base
        uses: github/super-linter@v4
            
        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
...